### PR TITLE
make pypff Python3 compatible

### PR DESCRIPTION
**Pull request by TimRepke**
I constantly got errors by setup.py during installation of the package. After these changes (sorry, my IDE messed with the indentation) things worked for me using Python 3.6.6

Essentially, Python 3 handles str/bytes differently, that's all

### CODE REVIEW

**Comment by joachimmetz** [comment]
> Sorry, my IDE messed with the indentation

This makes it hard for me to see what has changed.

> I constantly got errors by setup.py during installation of the package

Can you provide me with the error messages?

Also know pypff is work in progress https://github.com/libyal/libpff/issues/2

**Comment by TimRepke** [comment]
> Can you provide me with the error messages?
Unfortunately not really. I do have this screenshot though. All the errors were along the same kind.
image

> Also know pypff is work in progress #2
I saw that but assumed it stagnated as it's from 2014. Everything else works fine, just the setup script had errors.

> This makes it hard for me to see what has changed.
True. Tried to fix it. Not sure if your interpreter is not as strict as mine, but I had to change some indentation, otherwise Python tells me, that the indentation is not all the same.

**Comment by joachimmetz** [comment]
> Unfortunately not really. I do have this screenshot though. All the errors were along the same kind.

Thanks, that is sufficient.

> I saw that but assumed it stagnated as it's from 2014. Everything else works fine, just the setup script had errors.

I have limited time to work on it.

> True. Tried to fix it. Not sure if your interpreter is not as strict as mine, but I had to change some indentation, otherwise Python tells me, that the indentation is not all the same.

I have a look to see what changed and make the changes manually. For your context setup.py is generated by https://github.com/libyal/libyal/blob/master/scripts/source-generate.py

**Comment by joachimmetz** [comment]
@TimRepke thanks for the proposed changes though I'll not directly merge this PR. Since setup.py is generated elsewhere and this PR will need some clean up. So'll incorporate the necessary changes and regenerate setup.py for libpff.

Tracking changes to setup.py in https://github.com/libyal/libyal/issues/63
I'll close this PR once a regenerated setup.py has been committed for libpff.

**Comment by joachimmetz** [comment]
Adopted version of proposed changes integrated into https://github.com/libyal/libpff/commit/fecb6912675472d39204642ba03835c9fbff5c16

**Pull request closed without merging**
